# Docker compose file for bearlike/REMS-for-Organisations

# Docker build related issues can be raised here:
# * https://github.com/bearlike/REMS-For-Organisations/issues/new?labels=Docker

# Execute by running:
# docker-compose up -d

version: '3'

services:
    database:
        image: mariadb:10.7.3-focal
        restart: always
        ports:
            # We recommend commenting the ports block for increased security.
            # Exposing the database port is intended only for debugging.
            - 3306:3306
        volumes:
            - database_volume:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d # Load SQL files during database creation
        environment:
            MYSQL_ROOT_PASSWORD: "0000"
            MYSQL_PASSWORD: "0000"
            MYSQL_DATABASE: "db_cms"
            MYSQL_USER: "cmsuser"

    app:
        image: krishnaalagiri/rems:1.1.6
        restart: always
        depends_on:
            - database
        ports:
            # <host port>:<container port (default=80)>
            - 8080:80
        volumes:
            # Replace generated_certificates_volume with a absolute path if you
            #   need direct access to the certificates. Usually not required.
            - "generated_certificates_volume:/var/www/html/public/Generated Certificate"
        environment:
            # * Edit docker/secrets_.php for other enviroiment variables.
            MYSQL_HOST: database
            MYSQL_PASSWORD: "0000"
            MYSQL_USER: "cmsuser"

volumes:
    database_volume:
    generated_certificates_volume:
